### ISSUE TITLE
Design for Mojo::Feed

### ISSUE THREAD

**Issue by dotandimet** [dotandimet/Mojolicious-Plugin-FeedReader#5]
Let's refactor this code so that it is a stand-alone RSS parser.

We could just drop the plugin-ish bits and rename the module Mojo::FeedReader, but maybe we can make the design nicer.

- A Mojo::Feed object represents a syndication feed (RSS/Atom). Mojo::DOM is the inspiration.
- parse_rss() will be called parse().
- find_feeds() will be called discover(), and return a promise.
- url() is the URL of the feed.
- items() returns a Mojo::Collection of feed items, which should probably also be wrapped (lazily) in objects.
- Lazy attributes will let us simplify the entry into the RSS parsing code: dom() is initialized by parsing body() which is set by decoding text() which is set by loading file() which is retrieved from url(). Look at Mojo::Message for guidance.
- Methods for working with items, beyond what Mojo::Collection already offers?
- Finally, method(s) to serialize the parsed feed back? Using Mojo::DOM manipulation or Mojo::Template?

**Comment by mdom** [comment]
Wow, sounds great! Can't wait for it! Let me know if i can help in any way!

**Comment by mohawk2** [comment]
One way to make this most explicit would be to have on `master` a sort of "spec" (eg `spec.md`?) which had class[es] and methods, then PR modifications to that for discussion.

**Comment by dotandimet** [comment]
A rough cut of the module is now here: https://github.com/dotandimet/Mojo-Feed
